### ISSUE TITLE
还有一件事，6.13版本apptrack cmakelist文件丢了一行

### ISSUE THREAD

**Issue by lightningsoon** [baidu/boteye#20]
target_link_libraries(${PROJECT_NAME}
 ${GLOG_LIBRARY}
 ${GFLAGS_LIBRARY}
 ${XP_LIBRARY}
 ${OpenCV_LIBRARIES}
 ${XP_DRIVER_LIBRARY}
)
少了一个${XP_DRIVER_LIBRARY}，导致**编译错误**出现这样

app_tracking.cpp:(.text+0x1f8d)：对‘XPDRIVER::XpSensorMultithread::run()’未定义的引用
app_tracking.cpp:(.text+0x2c34)：对‘XPDRIVER::XpSensorMultithread::stop()’未定义的引用
CMakeFiles/app_tracking.dir/app_tracking.cpp.o：在函数‘std::default_delete<XPDRIVER::XpSensorMultithread>::operator()(XPDRIVER::XpSensorMultithread*) const’中：
app_tracking.cpp:(.text._ZNKSt14default_deleteIN8XPDRIVER19XpSensorMultithreadEEclEPS1_[_ZNKSt14default_deleteIN8XPDRIVER19XpSensorMultithreadEEclEPS1_]+0x1e)：对‘XPDRIVER::XpSenrMultithread::~XpSensorMultithread()’未定义的引用

**Comment by lightningsoon** [comment]
不知道为什么你们能编译起来

**Comment by lightningsoon** [comment]
总觉得给的apptrack和自己编译这一份不是同一个程序

**Comment by zhanglei2015yy** [comment]
你测试0.8.5固件了么

**Comment by lightningsoon** [comment]
@zhanglei2015yy 
这里的意思是，给的makelist是有错误的，不知道你们为什么能编译出结果，就算我改了之后，编译出的可执行文件功能和官方的也不一样。
比如没有2D地图，有轨迹跟踪图。修改代码后，才差不多。
0.8.5固件跟这个问题没有关系，我也已经试过了。
新加的初始化摄像头那个类不知道什么理由，也没有手册，还是回到0.6.5版本

**Comment by zhanglei2015yy** [comment]
@lightningsoon 
你是怎么修改的代码？

**Comment by lightningsoon** [comment]
@zhanglei2015yy 
看他们源码和API注释

**Comment by yanghongtian** [comment]
确实是这样，这个问题很奇怪，有一些系统能编译过。不过这个问题我们在后来的版本FIXED了。
谢谢您的反馈

**Comment by yanghongtian** [comment]
@zhanglei2015yy 我们一周前发布了最新的版本，欢迎您的试用

**Comment by zhanglei2015yy** [comment]
多谢，已经下载安装了




--
发自我的网易邮箱手机智能版


在 2018-08-15 19:45:04，yanghongtian <notifications@github.com> 写道：
