### ISSUE TITLE
boteye-master编译错误

### ISSUE THREAD

**Issue by strongerLi1113** [baidu/boteye#22]
ubuntu 16.04 64位

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XP_DRIVER_LIBRARY
    linked by target "xp_sensor_logger" in directory /home/strong/XP_release/boteye-master/apps/xp_sensor_logger
XP_LIBRARY
    linked by target "app_tracking" in directory /home/strong/XP_release/boteye-master/apps/app_tracking
    linked by target "pose_receiver" in directory /home/strong/XP_release/boteye-master/apps/app_tracking
    linked by target "xp_sensor_logger" in directory /home/strong/XP_release/boteye-master/apps/xp_sensor_logger
    linked by target "cam_calibration" in directory /home/strong/XP_release/boteye-master/apps/cam_calibration

**Comment by yanghongtian** [comment]
抱歉这么久才回复你，出现这个问题的原因是你的boteye-master目录下没有lib_x86_64的目录，这个目录请参考我们的WIKI的build章节里面的Pre-built libraries，请将lib_x86_64.tar.gz下载下来解压到boteye-master目录下即可。

**Comment by strongerLi1113** [comment]
你们可以写一个目录树，这样就比较清晰了

**Comment by yanghongtian** [comment]
Hi, 麻烦你重新下载那个lib_x86_64.tar.gz，按照上面那个步骤再重新cmake 和make一下，抱歉我们的压缩文件里面漏了一个.so文件

**Comment by yanghongtian** [comment]
@strongerLi1113 如果这个问题解决了，能麻烦你帮忙关闭这个issue吗。如果一周后还没有得到您的反馈，我假设这个问题已经解决了，后续如果有其他问题，欢迎您反馈给我们
