### ISSUE TITLE
地图录制问题

### ISSUE THREAD

**Issue by woshidag** [baidu/boteye#23]
我录制的地图是这样的，都是不连续的点
![default](https://user-images.githubusercontent.com/5061338/42980845-bc2a90fc-8c0b-11e8-916b-0e1e564d24ce.png)

官方文档中录制的地图是这样的
![3080e7b2fd614e8a82b2fb62cabf0d9c](https://user-images.githubusercontent.com/5061338/42980849-c252cc06-8c0b-11e8-83eb-bd6cc6719da6.png)

我的机器配置是 i5 4260u CPU @1.40GHz * 4
系统：ubuntu 14.04 lts

请问是哪里出问题啦？

**Comment by RunziiMo** [comment]
你好，是因为你的地图太小了，路径点之间空隙比较大
