### ISSUE TITLE
这是需要升级固件吗？

### ISSUE THREAD

**Issue by HustMrZhang** [baidu/boteye#25]
ubuntu16.04 运行./app_tracking -sensor_type XP2 -calib_file xxxxx.yaml出现以下结果：

Find a Baidu_Robotics_vision_XP2S dev at /dev/video0
read_soft_version:get ioctl failed code 105 err Buffer size does not match control size
*** Please update firmware ***
read device_id ioctl failed code 105 err Buffer size does not match control size
E0821 15:48:21.849987 27370 app_tracking.cpp:625] !live::init_XP_sensor()

**Comment by mingyux** [comment]
Yes.  Please see https://github.com/baidu/boteye_sensor
