### ISSUE TITLE
这个是为什么呢？

### ISSUE THREAD

**Issue by v479038280** [baidu/boteye#3]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XP_LIBRARY

**Comment by VincentHFZ** [comment]
没找到 XP_LIBRARY，在XP_3rdparty_helper.cmake 修改 XP_LIBRARY的路径地址

**Comment by kiyology** [comment]
@v479038280 Did you download the pre-built libraries, as shown in wiki [here](https://github.com/baidu/boteye/wiki/Build#pre-built-libraries)

**Comment by kiyology** [comment]
Closing this as it's been inactive for 10 days.
