### ISSUE TITLE
Pre-built libraries:[Ubuntu 14.04 lib_x86_64.tar.gz] download error

### ISSUE THREAD

**Issue by Jueodu** [baidu/boteye#34]
Pre-built libraries-Ubuntu **14.04**(Updated 08-20-2018): lib_x86_64.tar.gz  download error

{"code":"RequestExpired","message":"Request has expired. Timestamp date is 2018-11-19T16:45:09+08:00","requestId":"c2c7199d-6f48-490e-bc16-c3387f9ce078"}

**Comment by mingyux** [comment]
We recently updated the SDK and dependencies as well.  Please try to download again. https://github.com/baidu/boteye/wiki/Build

**Comment by Jueodu** [comment]
Thanks!
