### ISSUE TITLE
 ERROR:unknown command line flag 'pb_save'

### ISSUE THREAD

**Issue by zhoubonan** [baidu/boteye#39]
执行保存地图指令发生错误

$./app_tracking -sensor_type XP2 -calib_file ~/XP_release/XPIAC2SET182550007.yaml -pb_save /tmp/room.pb
ERROR:unknown command line flag 'pb_save'

**Comment by zhoubonan** [comment]
好的,谢谢.
使用手册没有新版本的吧

**Comment by johnjin404** [comment]
wiki貌似没有更新

**Comment by zhoubonan** [comment]
好吧

**Comment by zhoubonan** [comment]
你好，我在使用百度这个boteye提供的范例程序重定位的时候还有点问题，你这边是可以的吧，能帮我看看吗？
不好意思打扰你，谢谢了。
