### ISSUE TITLE
求问：app_tracking.cpp的修改

### ISSUE THREAD

**Issue by zhoubonan** [baidu/boteye#46]
目前提供的范例里面是在导航的时候会通过UDP方式的发布导航的信息给guide_receiver或者底盘

想问一下，如果我想在 执行记录轨迹命令 开启时也可以通过UDP发一些指定的数据出去，在app_tracking.cpp中大致需要如何改动呢？

谢谢。

**Comment by mingyux** [comment]
Unfortunately, the feature you requested is *NOT* part of the boteyeSDK at this moment.  We only expose a callback function interface to send the ```GuideMessage``` (```guide_message_callback```), which will be triggered by the actuator.
