### ISSUE TITLE
请问 loop closure detected 的代码在哪

### ISSUE THREAD

**Issue by zhoubonan** [baidu/boteye#48]
我这边想在 闭环优化的时候 添加一些输出的内容和轨迹文件的保存
在app_tracking.cpp中没有找到具体代码所在的位置..
谢谢

**Comment by mingyux** [comment]
The map is serialized to a .pb file when exiting app_tracking.  We don't have an API for the feature you're requesting at this moment.  You may want to call XP_TRACKER::save_map explicitly. 
 https://github.com/baidu/boteye/blob/master/include/XP/app_api/xp_tracker.h#L115
