### ISSUE TITLE
mac 虚拟机下安装失败

### ISSUE THREAD

**Issue by loadstarCN** [baidu/boteye#6]
在mac下装了一个干净的ubuntu 16.04 LTS ,运行source 3rdparty_lib_lean/update.sh，终端闪崩。看不清楚什么错误，查询日志也没有结果。请问大概是什么问题？

**Comment by kiyology** [comment]
@loadstarCN 你好，虚拟机暂时是不支持的，抱歉造成误解，我会加入到wiki里面
