### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by szm88** [baidu/boteye#7]
1."Run the following command to extract it to your root directory(make sure the entire folder is included in the root directory, not just the contents within):
tar -xvf lib_x86_64.tar.gz"

"the root directory" is /home/user***/XP_release/boteye/apps!
2. I calibrate the camera useing the lastest code,but the image is wrong.
 I think you should use usb3.0,not usb2.0.
3.press spacebar can't save image.
take mouse on image and press spacebar !
4.get color image : XP3
5. -auto_gain true : ./xp_sensor_logger -record_path /tmp/record1 -sensor_type XP3 -calib_mode  -auto_gain true
6.      "./xp_sensor_logger -calib_verify -calib_yaml ./tmp/calib.yaml -sensor_type XP2"
should be  "./xp_sensor_logger -calib_verify -calib_yaml  /tmp/calib.yaml -sensor_type XP2"

**Comment by kiyology** [comment]
@szm88 Thanks for your advice. I'll add them to our wiki! :)
