### ISSUE TITLE
Glad to know this algorithm but encountered with confusions.

### ISSUE THREAD

**Issue by TiderFang** [baidu/boteye#9]
I happened to know this SLAM algorithm and I am quite curious about it.  But it's disappointing that I couldn't find ever any videos or implements of this SLAM algorithm describing its greatness as what the hector slam, cartographer and gmapping do.  Also there is no article related to it. As an open source SLAM algorithm, that's strange. Could you give me some tips for finding these treasure ?
I have read the `Tech Specs` in  the **introduction page**. Several questions appear as below:
1. SLAM laterncy < 10 us? Hard to believe. If its true, so it's a realtime algorithm. (Here I regard the SLAM laterncy as the map update rate).
2. Also I have no idea with the SLAM error concept.
Could anyone answer my confusions about this algorithm?
Best wishes.

**Comment by mingyux** [comment]
@TiderFang We're working hard to open source the core of our SLAM engine.  As for your questions:

**Comment by TiderFang** [comment]
I see.

**Comment by kiyology** [comment]
Closing this as it's inactive for 3 weeks.
